-- =====================================================================
-- TGTransco GIS — initial core schema
--
-- Equivalent to Alembic migration 0001_initial_core.py. Run this ONLY if
-- you want to apply the schema by hand instead of `alembic upgrade head`.
-- It ends by stamping gis.alembic_version with '0001', so Alembic will
-- correctly treat this revision as already applied.
--
--   Target : PostgreSQL @ 172.17.4.194, database `gisdata`
--   Creates: schema `gis` (application data)
--   Touches: nothing in `legacy_raw` — that stays a frozen archive
--
--   psql -h 172.17.4.194 -U postgres -d gisdata -f 001_initial_core.sql
-- =====================================================================

BEGIN;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE SCHEMA IF NOT EXISTS gis;

SET LOCAL search_path = gis, public;

-- ---------------------------------------------------------------- enums
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type t
                   JOIN pg_namespace n ON n.oid = t.typnamespace
                   WHERE t.typname = 'user_role' AND n.nspname = 'gis') THEN
        CREATE TYPE gis.user_role AS ENUM ('admin', 'editor', 'viewer');
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_type t
                   JOIN pg_namespace n ON n.oid = t.typnamespace
                   WHERE t.typname = 'equipment_kind' AND n.nspname = 'gis') THEN
        CREATE TYPE gis.equipment_kind AS ENUM
            ('shunt_reactor', 'capacitor', 'station_transformer');
    END IF;
END
$$;

-- ------------------------------------------------------------- app_user
CREATE TABLE gis.app_user (
    id                   integer       GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username             varchar(50)   NOT NULL,
    full_name            varchar(120),
    password_hash        varchar(128)  NOT NULL,
    role                 gis.user_role NOT NULL DEFAULT 'viewer',
    is_active            boolean       NOT NULL DEFAULT true,
    must_change_password boolean       NOT NULL DEFAULT true,
    created_at           timestamptz   NOT NULL DEFAULT now(),
    updated_at           timestamptz   NOT NULL DEFAULT now(),
    last_login_at        timestamptz,
    CONSTRAINT pk_app_user          PRIMARY KEY (id),
    CONSTRAINT uq_app_user_username UNIQUE (username)
);

CREATE INDEX ix_app_user_username ON gis.app_user (username);

-- ----------------------------------------------------------- substation
-- Normalized rebuild of legacy_raw."substations-template" (143 flat columns).
CREATE TABLE gis.substation (
    ss_code                bigint NOT NULL,

    -- identity / classification
    ss_name                varchar(200),
    ss_type                varchar(50),
    volt_class             varchar(50),
    volt_levels            varchar(50),
    primary_mva_cap        numeric(12, 2),
    no_of_ptrs             smallint,

    -- administrative hierarchy
    district               varchar(150),
    zone                   varchar(100),
    circle                 varchar(100),
    division               varchar(150),
    plant_circle           varchar(100),

    -- attributes / flags (free text — legacy values are inconsistent)
    manned                 varchar(50),
    generation             varchar(50),
    gen_type               varchar(100),
    scada                  varchar(50),
    railway_tss            varchar(50),
    gis_type               varchar(50),
    ehv_consumer           varchar(50),
    rad_grid               varchar(50),
    dg_set                 varchar(50),
    dg_and_ff_system       varchar(50),
    contact_no             varchar(50),

    -- codes / external references
    function_loc_code      varchar(100),
    sap_erp_connectivity   varchar(50),
    rrsc_ss_code           varchar(50),
    ss_erp_source          varchar(100),

    -- document links
    ss_doc                 text,
    link_sld               text,
    link_ss_photo          text,
    link_ss_layout         text,

    -- geometry: longitude/latitude -> location, long1..long15/lat1..lat15 -> boundary
    location               geography(Point, 4326),
    boundary               geography(Polygon, 4326),

    -- audit
    inserted_by            varchar(50),
    inserted_at            timestamptz,
    updated_by             varchar(50),
    updated_at             timestamptz DEFAULT now(),

    CONSTRAINT pk_substation PRIMARY KEY (ss_code)
);

CREATE INDEX ix_substation_location    ON gis.substation USING gist (location);
CREATE INDEX ix_substation_boundary    ON gis.substation USING gist (boundary);
CREATE INDEX ix_substation_volt_class  ON gis.substation (volt_class);
CREATE INDEX ix_substation_zone_circle ON gis.substation (zone, circle);

-- ---------------------------------------------------------- transformer
-- One row per legacy ptr1_*..ptr9_* slot.
CREATE TABLE gis.transformer (
    id                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ss_code               bigint   NOT NULL,
    slot_no               smallint NOT NULL,
    capacity_mva          numeric(12, 2),
    serial_no             varchar(150),
    make                  varchar(150),
    vector_group          varchar(50),
    year_of_commissioning date,
    yoc_raw               varchar(100),   -- original ptrN_yoc text, unparsed
    po_reference          text,
    volt_level            varchar(50),
    CONSTRAINT pk_transformer                 PRIMARY KEY (id),
    CONSTRAINT fk_transformer_ss_code_substation
        FOREIGN KEY (ss_code) REFERENCES gis.substation (ss_code) ON DELETE CASCADE,
    CONSTRAINT uq_transformer_ss_code         UNIQUE (ss_code, slot_no),
    CONSTRAINT ck_transformer_slot_no_range   CHECK (slot_no BETWEEN 1 AND 9)
);

CREATE INDEX ix_transformer_ss_code ON gis.transformer (ss_code);

-- ------------------------------------------------- substation_equipment
-- shunt reactor / capacitor / station transformer.
CREATE TABLE gis.substation_equipment (
    id                    integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ss_code               bigint NOT NULL,
    kind                  gis.equipment_kind NOT NULL,
    capacity_mva          numeric(12, 2),
    serial_no             varchar(150),
    make                  varchar(150),
    vector_group          varchar(50),
    year_of_commissioning date,
    yoc_raw               varchar(100),
    po_reference          text,
    CONSTRAINT pk_substation_equipment PRIMARY KEY (id),
    CONSTRAINT fk_substation_equipment_ss_code_substation
        FOREIGN KEY (ss_code) REFERENCES gis.substation (ss_code) ON DELETE CASCADE
);

CREATE INDEX ix_substation_equipment_ss_code ON gis.substation_equipment (ss_code);

-- --------------------------------------------- stamp the Alembic version
-- So a later `alembic upgrade head` does not try to re-apply revision 0001.
CREATE TABLE IF NOT EXISTS gis.alembic_version (
    version_num varchar(32) NOT NULL,
    CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
);

INSERT INTO gis.alembic_version (version_num)
VALUES ('0001')
ON CONFLICT (version_num) DO NOTHING;

COMMIT;

-- =====================================================================
-- Verify
-- =====================================================================
-- \dn                                  -- schemas: gis, legacy_raw, dbo, public
-- \dt gis.*                            -- 5 tables incl. alembic_version
-- SELECT postgis_full_version();
-- SELECT version_num FROM gis.alembic_version;   -- 0001
