-- =====================================================================
-- 005 — solar plants, EHV consumers, and three read-only reference layers
--
--   gis.solar_plant       from legacy_raw."Solar Plants"       (57 rows)
--   gis.ehv_consumer      from legacy_raw."ehvconsumers"       (127 rows)
--   gis.pgcil_substation  from legacy_raw.pgcil                (6 rows)
--   gis.hydel_power_station from legacy_raw.hydelpowerstations (11 rows)
--   gis.pgcil_line        from legacy_raw.pgcillines           (1,959 rows)
--
-- The last three are read-only: no INSERT/UPDATE against pgcil,
-- hydelpowerstations or pgcillines exists anywhere in the legacy stored
-- procedures, and no .aspx page edits them - only MapView.aspx displays
-- them. So no write-path columns (inserted_by etc.) and no service-layer
-- create/update logic will be built for these three.
--
-- pgcil_line has no ordering column in the source at all, so it is a point
-- layer, not a route - see the model docstring in app/models/pgcil.py.
--
--   psql -h 172.17.4.194 -U postgres -d gisdata -f 005_add_solar_ehv_pgcil_hydel.sql
-- =====================================================================

BEGIN;

SET LOCAL search_path = gis, public;

-- ---------------------------------------------------------- solar_plant
CREATE TABLE gis.solar_plant (
    solar_id                 bigint NOT NULL,
    plant_name                text,
    location_desc             text,
    installed_capacity_mw     numeric(10, 2),
    interfacing_ss            text,
    voltage_level             varchar(50),
    commercial_operation_date date,
    location                  geography(Point, 4326),
    division                  varchar(100),
    circle                    varchar(100),
    zone                      varchar(100),
    CONSTRAINT pk_solar_plant PRIMARY KEY (solar_id)
);
CREATE INDEX ix_solar_plant_location ON gis.solar_plant USING gist (location);

-- --------------------------------------------------------- ehv_consumer
CREATE TABLE gis.ehv_consumer (
    ehv_id                bigint NOT NULL,
    name                   text,
    location_desc          text,
    installed_capacity_mw  numeric(10, 2),
    location               geography(Point, 4326),
    feeder_id              integer,
    feeder_name            text,
    substation             text,
    consumer_code          varchar(100),
    voltage_rate           varchar(50),
    function_loc_code      varchar(100),
    connected_ss           text,
    line_name              text,
    line_code              varchar(100),
    division               varchar(100),
    circle                 varchar(100),
    zone                   varchar(100),
    CONSTRAINT pk_ehv_consumer PRIMARY KEY (ehv_id),
    CONSTRAINT fk_ehv_consumer_feeder_id_line
        FOREIGN KEY (feeder_id) REFERENCES gis.line (feeder_id) ON DELETE SET NULL
);
CREATE INDEX ix_ehv_consumer_location  ON gis.ehv_consumer USING gist (location);
CREATE INDEX ix_ehv_consumer_feeder_id ON gis.ehv_consumer (feeder_id);

-- ------------------------------------------------------- pgcil_substation
CREATE TABLE gis.pgcil_substation (
    id       integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    voltage  text,
    name     text,
    location geography(Point, 4326),
    CONSTRAINT pk_pgcil_substation PRIMARY KEY (id)
);
CREATE INDEX ix_pgcil_substation_location ON gis.pgcil_substation USING gist (location);

-- ----------------------------------------------------- hydel_power_station
CREATE TABLE gis.hydel_power_station (
    hydel_id      integer NOT NULL,
    name          varchar(255),
    gen_cap_mw    numeric(10, 2),
    connected_ss  varchar(100),
    volt_level    varchar(10),
    division      varchar(100),
    circle        varchar(50),
    zone          varchar(100),
    location      geography(Point, 4326),
    CONSTRAINT pk_hydel_power_station PRIMARY KEY (hydel_id)
);
CREATE INDEX ix_hydel_power_station_location ON gis.hydel_power_station USING gist (location);

-- ------------------------------------------------------------- pgcil_line
CREATE TABLE gis.pgcil_line (
    id           integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    feeder_name  text,
    location     geography(Point, 4326),
    CONSTRAINT pk_pgcil_line PRIMARY KEY (id)
);
CREATE INDEX ix_pgcil_line_location ON gis.pgcil_line USING gist (location);
CREATE INDEX ix_pgcil_line_feeder_name ON gis.pgcil_line (feeder_name);

UPDATE gis.alembic_version SET version_num = '0005';

COMMIT;

-- =====================================================================
-- Verify
-- =====================================================================
-- SELECT version_num FROM gis.alembic_version;   -- 0005
